language: node_js
node_js:
  - "10"
sudo: required
addons:
  apt:
    packages:
      - docker-ce

services:
  - docker


before_install:

  - docker-compose  build
  - docker-compose up -d mongo

script:
  - docker-compose run back-end sh -c "npm run test-auth"


after_script:
  - cd Docker; docker-compose down -v --rmi all
