version: "2"

services:
  front-end:
    build: front-end
    ports:
      - "4200:4200"
    container_name: front-container
    restart: always
  back-end:
          container_name: back-container
          build: back-end
          ports:
            - "3000:3000"
          restart: always
          depends_on:
            - mongo
  mongo:
      image: mongo
      ports:
        - "27017:27017"


    
